# Generated by Django 5.1 on 2024-08-24 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_completed',
            new_name='datecompleted',
        ),
    ]
