# Generated by Django 5.1 on 2024-09-03 22:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_profile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
